import enum
from enum import Enum


class Gender(str, Enum):
    MALE = "مرد"
    FEMALE = "زن"
    OTHERS = "سایر"


class Brand(str, Enum):
    TOYOTA = "toyota"
    FORD = "ford"
    HONDA = "honda"
    BMW = "bmw"
    MERCEDES_BENZ = "mercedes-benz"
    AUDI = "audi"
    CHEVROLET = "chevrolet"
    NISSAN = "nissan"
    VOLKSWAGEN = "volkswagen"
    HYUNDAI = "hyundai"
    KIA = "kia"
    SUBARU = "subaru"
    MAZDA = "mazda"
    VOLVO = "volvo"
    LAND_ROVER = "land_rover"
    JEEP = "jeep"
    PORSCHE = "porsche"
    FIAT = "fiat"
    LEXUS = "lexus"
    DODGE = "dodge"
    ACURA = "acura"
    INFINITI = "infiniti"
    GMC = "gmc"
    SMART = "smart"
    MINI = "mini"
    RENAULT = "renault"
    PEUGEOT = "peugeot"
    CITROEN = "citroën"
    SEAT = "seat"
    SKODA = "skoda"
    MASERATI = "maserati"
    FERRARI = "ferrari"
    LAMBORGHINI = "lamborghini"
    BUGATTI = "bugatti"
    TESLA = "tesla"
    SUZUKI = "suzuki"
    OPEL = "opel"
    MITSUBISHI = "mitsubishi"
    ISUZU = "isuzu"
    DAEWOO = "daewoo"
    MG = "mg"
    GREAT_WALL = "great_wall"
    BYD = "byd"
    CHERY = "chery"
    GEELY = "geely"
    FISKER = "fisker"
    ROLLS_ROYCE = "rolls-royce"
    BENTLEY = "bentley"
    ASTON_MARTIN = "aston_martin"
    ALFA_ROMEO = "alfa_romeo"
    LADA = "lada"
    DAIHATSU = "daihatsu"
    CHRYSLER = "chrysler"
    PONTIAC = "pontiac"
    SCION = "scion"


class CarColor(str, Enum):
    BLACK = "black"
    WHITE = "white"
    GRAY = "gray"
    SILVER = "silver"
    RED = "red"
    BLUE = "blue"
    GREEN = "green"
    YELLOW = "yellow"
    ORANGE = "orange"
    BROWN = "brown"
    GOLD = "gold"
    PURPLE = "purple"
    PINK = "pink"
    JET_BLACK = "jet_black"
    MATTE_BLACK = "matte_black"
    CHARCOAL = "charcoal"
    GRAPHITE = "graphite"
    ANTHRACITE = "anthracite"
    PEARL_WHITE = "pearl_white"
    IVORY = "ivory"
    ALABASTER = "alabaster"
    CRIMSON = "crimson"
    MAROON = "maroon"
    BURGUNDY = "burgundy"
    CHERRY_RED = "cherry_red"
    RUBY_RED = "ruby_red"
    WINE_RED = "wine_red"
    NAVY_BLUE = "navy_blue"
    SKY_BLUE = "sky_blue"
    TURQUOISE = "turquoise"
    TEAL = "teal"
    COBALT_BLUE = "cobalt_blue"
    ROYAL_BLUE = "royal_blue"
    ELECTRIC_BLUE = "electric_blue"
    FOREST_GREEN = "forest_green"
    OLIVE_GREEN = "olive_green"
    LIME_GREEN = "lime_green"
    EMERALD_GREEN = "emerald_green"
    MINT_GREEN = "mint_green"
    JADE_GREEN = "jade_green"
    MUSTARD_YELLOW = "mustard_yellow"
    CANARY_YELLOW = "canary_yellow"
    AMBER = "amber"
    BRONZE = "bronze"
    CHAMPAGNE = "champagne"
    COPPER = "copper"
    CORAL = "coral"
    PEACH = "peach"
    APRICOT = "apricot"
    CHOCOLATE_BROWN = "chocolate_brown"
    COFFEE = "coffee"
    MAHOGANY = "mahogany"
    LAVENDER = "lavender"
    MAUVE = "mauve"
    INDIGO = "indigo"
    VIOLET = "violet"
    MAGENTA = "magenta"
    ROSE_PINK = "rose_pink"
    FUCHSIA = "fuchsia"
    MIDNIGHT_BLUE = "midnight_blue"
    NEON_GREEN = "neon_green"
    SUNBURST_ORANGE = "sunburst_orange"
    PLATINUM = "platinum"
    TITANIUM = "titanium"
    OBSIDIAN = "obsidian"
    CHROME = "chrome"
    PEARLESCENT = "pearlescent"
    HOLOGRAPHIC = "holographic"
    MATTE_GRAY = "matte_gray"
    MATTE_RED = "matte_red"
    MATTE_BLUE = "matte_blue"
    MATTE_GREEN = "matte_green"
    MATTE_YELLOW = "matte_yellow"
    MATTE_PURPLE = "matte_purple"
    MATTE_ORANGE = "matte_orange"
    TWO_TONE = "two-tone"
    OMBRE = "ombre"
    CAMOUFLAGE = "camouflage"


class CarStatus(str, Enum):
    NEW = "نو"
    AVAILABLE = "موجود"
    RENTED = "اجاره شده"
    MAINTENANCE = "در سرویس"
    DAMAGED = "آسیب‌دیده"
    UNKNOWN = "نامشخص"


class InsuranceType(str, Enum):
    ThirdParty = "شخص ثالث"
    PassengerAccident = "حوادث سرنشین"
    VehicleBody = "بدنه خودرو"


class BranchLocations(str, Enum):
    TEHRAN = "تهران"
    MASHHAD = "مشهد"
    ISFAHAN = "اصفهان"
    SHIRAZ = "شیراز"
    TABRIZ = "تبریز"
    KISH = "کیش"
    QOM = "قم"
    AHVAZ = "اهواز"
    RASHT = "رشت"
    KERMAN = "کرمان"
    HAMEDAN = "همدان"
    YAZD = "یزد"
    URMIA = "ارومیه"
    BANDARABBAS = "بندرعباس"
    BUSHEHR = "بوشهر"


class PaymentMethod(str, Enum):
    CARD_TO_CARD = "انتقال وجه کارت به کارت"
    SATNA = "انتقال وجه ساتنا"
    PAYA = "انتقال وجه پایا"
    ONLINE_PAYMENT = "پرداخت اینترنتی"
    OTHER = "سایر"


class PaymentStatus(str, Enum):
    CREATED = "ایجاد شده"
    PENDING = "در انتظار تایید"
    COMPLETED = "تایید شده"
    FAILED = "ناموفق"
    CANCELED = "لغو شده"
    REFUNDED = "بازگشت مبلغ پرداختی"
    PARTIALLY_REFUNDED = "بازگشت بخشی از مبلغ پرداختی"
    EXPIRED = "منقضی شده"


class AdminRole(str, Enum):
    SUPER_ADMIN = "SuperAdmin"
    GENERAL_ADMIN = "Admin"
    # FLEET_ADMIN = "FleetAdmin"
    # FINANCIAL_ADMIN = "FinancialAdmin"
    # RESERVATION_ADMIN = "ReservationAdmin"


class CustomerRole(str, Enum):
    CUSTOMER = "Customer"


class AdminStatus(str, Enum):
    ACTIVE = "فعال"
    INACTIVE = "غیر فعال"


class InvoiceStatus(str, Enum):
    CREATED = "ایجاد شده"
    PENDING = "در انتظار تایید"
    COMPLETED = "تایید شده"
    FAILED = "ناموفق"
    CANCELED = "لغو شده"
    EXPIRED = "منقضی شده"


class LogicalOperator(str, Enum):
    AND = "and"
    OR = "or"
    NOT = "not"


class CommentSubject(str, Enum):
    BUG = "گزارش مشکل"
    FEATURE_REQUEST = "درخواست ویژگی جدید"
    QUESTION = "سوال"
    FEEDBACK = "بازخورد"
    SUGGESTION = "پیشنهاد"
    CRITICISM = "انتقاد"


class CommentStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    SPAM = "spam"
